---
name: upload_coverage_report

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

env:
  REPORT_NAME: "coverage.out"

jobs:
  upload_coverage_report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.18'
      - name: Generate code coverage
        run: |
          go test -coverprofile="${{ env.REPORT_NAME }}" ./...
      - name: Upload coverage to codecov (tokenless)
        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name != github.repository
        uses: codecov/codecov-action@v5
        with:
          files: "${{ env.REPORT_NAME }}"
          fail_ci_if_error: true
      - name: Upload coverage to codecov (with token)
        if: "! github.event.pull_request.head.repo.fork "
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: "${{ env.REPORT_NAME }}"
          fail_ci_if_error: true
...
